### ISSUE TITLE
Issue #9 : Implement GitHub Actions for CI/CD Pipeline

### ISSUE THREAD

**Issue by Rapter1990** [Rapter1990/todowithcouchbase#10]
**Description:**

- **Task:** Set up GitHub Actions to automate the build, test, and deployment processes for the To-Do List project. This will help ensure that code changes are automatically tested and deployed efficiently.

### **Steps to Complete:**

1. **Create GitHub Actions Workflow:**
   - Add a new workflow file in the `.github/workflows` directory (e.g., `ci-cd.yml`).

   **Sample Workflow File:**
   ```yaml
   name: CI/CD Pipeline

   on:
     push:
       branches:
         - main
     pull_request:
       branches:
         - main

   jobs:
     build:
       runs-on: ubuntu-latest

       steps:
         - name: Checkout code
           uses: actions/checkout@v2

         - name: Set up JDK 17
           uses: actions/setup-java@v2
           with:
             java-version: '17'

         - name: Build with Maven
           run: mvn clean package

         - name: Run Tests
           run: mvn test

         - name: Publish to Docker Hub
           if: github.event_name == 'push'
           env:
             DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
             DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
           run: |
             echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
             docker build -t your-username/todo-app .
             docker push your-username/todo-app
   ```

2. **Set Up Secrets:**
   - Go to the repository settings, and under "Secrets and variables," add secrets for `DOCKER_USERNAME` and `DOCKER_PASSWORD` to allow publishing to Docker Hub.

3. **Customize Build and Test Commands:**
   - Modify the build and test commands according to your project setup. If you are using Gradle or another build tool, adjust the relevant commands.

4. **Add Deployment Steps (Optional):**
   - If applicable, add steps to deploy the application to a cloud service or server after a successful build and test.

5. **Test the Workflow:**
   - Push changes to the main branch or create a pull request to trigger the workflow. Verify that the actions run successfully and produce the expected results.

6. **Documentation:**
   - Update the project documentation to include information on how the GitHub Actions workflow is set up and any configurations needed for developers.

### **Acceptance Criteria:**
- GitHub Actions workflow is created and successfully builds the project.
- All tests are executed, and results are reported in the Actions tab.
- Optionally, the application is published to Docker Hub upon successful build on the main branch.
- Secrets for Docker Hub are configured securely.

---
