### ISSUE TITLE
Issue #7 : Dockerize the To-Do List Project (Spring Boot + Couchbase)  

### ISSUE THREAD

**Issue by Rapter1990** [Rapter1990/todowithcouchbase#7]
---

**Title:** Dockerize the To-Do List Project (Spring Boot + Couchbase)  

**Description:**  
- **Task:** Implement Dockerization for the to-do list project by creating a `Dockerfile` for the Spring Boot application, a `docker-compose.yml` file to orchestrate the Spring Boot service and Couchbase.

### **Steps to Complete:**

1. **Create Dockerfile for Spring Boot Application:**
   - Use a multi-stage build to optimize the image size.
   - The first stage should build the Spring Boot application using a Java JDK image.
   - The second stage should use a lightweight Java JRE image to run the application.
   - Ensure the application exposes the necessary port (e.g., `8080`).

   **Sample Dockerfile:**
   ```dockerfile
   # Stage 1: Build the application
   FROM maven:3.8.6-openjdk-17 AS builder
   WORKDIR /app
   COPY . .
   RUN mvn clean package -DskipTests

   # Stage 2: Run the application
   FROM openjdk:17-jdk-slim
   WORKDIR /app
   COPY --from=builder /app/target/todo-app.jar /app/todo-app.jar
   EXPOSE 8080
   ENTRYPOINT ["java", "-jar", "todo-app.jar"]
   ```

2. **Create `docker-compose.yml` File:**
   - Define services for the Spring Boot application, Couchbase.
   - Configure the Couchbase service to expose the required ports (default: `8091`, `8092`, `8093`, `11210`).
   - Set environment variables for Couchbase in the `docker-compose.yml` (e.g., username, password).
   - Link the Spring Boot app to the Couchbase container for communication.

   **Sample `docker-compose.yml`:**
   ```yaml
   version: '3'
   services:
     couchbase:
       image: couchbase:latest
       container_name: couchbase
       ports:
         - "8091:8091"
         - "8092:8092"
         - "8093:8093"
         - "11210:11210"
       environment:
         - COUCHBASE_ADMINISTRATOR_USERNAME=admin
         - COUCHBASE_ADMINISTRATOR_PASSWORD=password
       volumes:
         - couchbase_data:/opt/couchbase/var

     app:
       build:
         context: .
         dockerfile: Dockerfile
       ports:
         - "8080:8080"
       environment:
         - SPRING_DATA_COUCHBASE_BUCKET=my_bucket
         - SPRING_DATA_COUCHBASE_USERNAME=admin
         - SPRING_DATA_COUCHBASE_PASSWORD=password
         - SPRING_DATA_COUCHBASE_HOST=couchbase
       depends_on:
         - couchbase
   volumes:
     couchbase_data:
   ```

3. **Configure Spring Boot Application:**
   - Update the `application.properties` or `application.yml` to configure Couchbase connectivity using environment variables.
   - Sample properties:
     ```properties
     spring.couchbase.connection-string=couchbase://couchbase
     spring.couchbase.username=${COUCHBASE_ADMINISTRATOR_USERNAME}
     spring.couchbase.password=${COUCHBASE_ADMINISTRATOR_PASSWORD}
     spring.couchbase.bucket.name=${SPRING_DATA_COUCHBASE_BUCKET}
     ```

4. **Test the Setup:**
   - Run `docker-compose up` to start the containers.
   - Verify that the Couchbase instance is running and accessible via its management interface (e.g., `http://localhost:8091`).
   - Ensure the Spring Boot application connects to Couchbase and performs CRUD operations on the to-do list items.

---
