### ISSUE TITLE
Issue #8 : Integrate Prometheus and Grafana for Monitoring

### ISSUE THREAD

**Issue by Rapter1990** [Rapter1990/todowithcouchbase#8]
**Description:**

- **Task:** Add monitoring capabilities to the To-Do List project by integrating Prometheus and Grafana. This will include configuring Prometheus for metrics scraping and setting up Grafana to visualize the metrics.

### **Steps to Complete:**

1. **Prometheus Configuration:**
   - Create a `prometheus.yml` configuration file to define the scrape settings for the Spring Boot application.
   - Set the scrape interval and the target endpoint for metrics exposure (default Spring Boot Actuator metrics endpoint).

   **Sample `prometheus.yml`:**
   ```yaml
   global:
     scrape_interval: 15s  # Set the scrape interval to 15 seconds.

   scrape_configs:
     - job_name: 'todo-app'
       static_configs:
         - targets: ['app:8080']  # Replace 'app' with the name of your Spring Boot service in Docker.
   ```

2. **Docker Compose Update:**
   - Modify the existing `docker-compose.yml` file to include Prometheus and Grafana services.
   - Configure Grafana to connect to Prometheus as a data source.

   **Updated `docker-compose.yml`:**
   ```yaml
   version: '3'
   services:
     couchbase:
       image: couchbase:latest
       container_name: couchbase
       ports:
         - "8091:8091"
         - "8092:8092"
         - "8093:8093"
         - "11210:11210"
       environment:
         - COUCHBASE_ADMINISTRATOR_USERNAME=admin
         - COUCHBASE_ADMINISTRATOR_PASSWORD=password
       volumes:
         - couchbase_data:/opt/couchbase/var

     app:
       build:
         context: .
         dockerfile: Dockerfile
       ports:
         - "8080:8080"
       environment:
         - SPRING_DATA_COUCHBASE_BUCKET=my_bucket
         - SPRING_DATA_COUCHBASE_USERNAME=admin
         - SPRING_DATA_COUCHBASE_PASSWORD=password
         - SPRING_DATA_COUCHBASE_HOST=couchbase
       depends_on:
         - couchbase

     prometheus:
       image: prom/prometheus:latest
       container_name: prometheus
       ports:
         - "9090:9090"
       volumes:
         - ./prometheus.yml:/etc/prometheus/prometheus.yml
       command:
         - --config.file=/etc/prometheus/prometheus.yml

     grafana:
       image: grafana/grafana:latest
       container_name: grafana
       ports:
         - "3000:3000"
       environment:
         - GF_SECURITY_ADMIN_PASSWORD=admin  # Set Grafana admin password
       depends_on:
         - prometheus

   volumes:
     couchbase_data:
   ```

3. **Set Up Grafana Dashboard:**
   - After starting the containers, access Grafana at `http://localhost:3000` with the admin credentials defined above.
   - Add Prometheus as a data source:
     - URL: `http://prometheus:9090`
   - Create a dashboard to visualize the metrics collected from the Spring Boot application.

4. **Expose Spring Boot Actuator Metrics:**
   - Ensure that the Spring Boot application is configured to expose metrics by adding the necessary dependencies to your `pom.xml` or `build.gradle` file:
     ```xml
     <dependency>
         <groupId>org.springframework.boot</groupId>
         <artifactId>spring-boot-starter-actuator</artifactId>
     </dependency>
     <dependency>
         <groupId>io.micrometer</groupId>
         <artifactId>micrometer-registry-prometheus</artifactId>
     </dependency>
     ```

   - Enable metrics in the `application.properties` or `application.yml`:
     ```properties
     management.endpoints.web.exposure.include=*
     management.endpoint.prometheus.enabled=true
     ```

### **Acceptance Criteria:**
- Prometheus should be able to scrape metrics from the Spring Boot application.
- Grafana should display the collected metrics in a dashboard.
- Ensure the monitoring stack is running without errors and accessible via the specified ports.

---
